### PR TITLE
fix: use provided fetcher to fetch jwks

### PR DESCRIPTION
**Pull request by bukowskiadam**
I had to do some magic tricks to keep the fetcher's interface the same because JwksClient expects to just return the jwks.

This PR is more for a discussion, maybe we should use a different fetch implementation for this purpose. I've checked it and JwksClient uses node http or https agent.

### CODE REVIEW

**Comment by joawan** [comment]
JwksClient also supports overriding `requestAgent` but I'd say the fetcher is more flexible. I see the magic, but looks alright. It's possible to add some extra magic, to not send in { fetcher: false }, but might be be unnecessary.

I noticed that the custom fetcher removes support for `timeout`, `requestHeaders`, `requestAgent`. `timeout` is a configurable via the `jwks_timeout` setting of the lib. This change will always ignore that timeout, since [fetch is always set in options](https://github.com/schibsted/node-token-introspection/blob/master/src/index.js#L25-L27) when using main entry point.

This lib uses node-fetch v2 at the comment and it [supports timeout](https://github.com/node-fetch/node-fetch/tree/2.x?tab=readme-ov-file#options) but recommends using AbortSignal instead. Timeout option is removed in node-fetch v3.

I'll explore a bit what to do with the timeout option. Could be we just add it as an option and for the v2 case.

**Comment by bukowskiadam** [comment]
I get the point of the timeout and using our node-fetch always in JwksClient and that's changing too much. So maybe something like this:
image
image
Separate fetch key from the fetch jwks?

**Comment by joawan** [comment]
That's another option that limits unforeseen consequences a lot. Would just need to make a note in the docs that timeout isn't respected when using custom jwks fetcher and that those would be needed to be handled by the custom fetcher.

**Comment by bukowskiadam** [comment]
Sorry, I'm pretty busy with other stuff. I'll redo it as we agreed ☝🏻 and push commits here

**Review by joawan — APPROVED** [review]
LGTM

**Pull request merged**
